import geometryData from './data/geometry.json'

// Generated by service/scripts/build_web_geometry.py from the static GTFS
// metro-mode snapshot. Refreshed by hand -- a bundled file rather than a
// live endpoint, by design.

export interface Station {
  id: string
  name: string
  lat: number
  lon: number
}

export interface Route {
  id: string
  name: string
  color: string
  stationIds: string[]
  /** [lon, lat] pairs tracing the real rail alignment (GTFS shapes.txt),
   * not a straight line between stations. Falls back to straight-line
   * station coordinates only if the build script found no usable shape
   * for a route (see build_web_geometry.py). */
  shape: [number, number][]
}

export interface Bounds {
  west: number
  east: number
  south: number
  north: number
}

export interface Geometry {
  stations: Station[]
  routes: Route[]
  bounds: Bounds
}

export const geometry = geometryData as Geometry

/** Builds the three lookup indexes any geometry set needs -- shared by
 * Metro's `geometry.json` and V/Line's `vline-geometry.json` (see
 * `vlineGeometry.ts`) so both go through one implementation. */
export function buildGeometryIndex(source: Geometry): {
  stationsById: Map<string, Station>
  routesById: Map<string, Route>
  routesByStationId: Map<string, Set<string>>
} {
  const stationsById = new Map(source.stations.map((s) => [s.id, s]))
  const routesById = new Map(source.routes.map((r) => [r.id, r]))

  // Which routes actually serve each station -- needed so toggling one
  // line off doesn't hide a station still served by another visible line
  // (e.g. an interchange), and so selecting a station (search or map
  // click) can tell which of its lines, if any, are currently hidden.
  const routesByStationId = new Map<string, Set<string>>()
  for (const route of source.routes) {
    for (const stationId of route.stationIds) {
      if (!routesByStationId.has(stationId)) routesByStationId.set(stationId, new Set())
      routesByStationId.get(stationId)!.add(route.id)
    }
  }

  return { stationsById, routesById, routesByStationId }
}

const metroIndex = buildGeometryIndex(geometry)
export const stationsById = metroIndex.stationsById
export const routesById = metroIndex.routesById
export const routesByStationId = metroIndex.routesByStationId
