import geometryData from './data/geometry.json'

// Generated by service/scripts/build_web_geometry.py from the static GTFS
// metro-mode snapshot. Refreshed by hand — see work-docs milestones/04-map.md
// ("Local preview approach" / Stage 2) for why this is a bundled file rather
// than a live endpoint.

export interface Station {
  id: string
  name: string
  lat: number
  lon: number
}

export interface Route {
  id: string
  name: string
  color: string
  stationIds: string[]
  /** [lon, lat] pairs tracing the real rail alignment (GTFS shapes.txt),
   * not a straight line between stations. Falls back to straight-line
   * station coordinates only if the build script found no usable shape
   * for a route (see build_web_geometry.py). */
  shape: [number, number][]
}

export interface Bounds {
  west: number
  east: number
  south: number
  north: number
}

export interface Geometry {
  stations: Station[]
  routes: Route[]
  bounds: Bounds
}

export const geometry = geometryData as Geometry

export const stationsById = new Map(geometry.stations.map((s) => [s.id, s]))
export const routesById = new Map(geometry.routes.map((r) => [r.id, r]))

// Which routes actually serve each station -- needed so toggling one line
// off doesn't hide a station still served by another visible line (e.g. an
// interchange), and so selecting a station (search or map click) can tell
// which of its lines, if any, are currently hidden. Shared by
// map/mapController.ts and components/Search.tsx -- computed once here
// rather than twice.
export const routesByStationId = new Map<string, Set<string>>()
for (const route of geometry.routes) {
  for (const stationId of route.stationIds) {
    if (!routesByStationId.has(stationId)) routesByStationId.set(stationId, new Set())
    routesByStationId.get(stationId)!.add(route.id)
  }
}
