import geometryData from './data/geometry.json'

// Generated by service/scripts/build_web_geometry.py from the static GTFS
// metro-mode snapshot. Refreshed by hand — see work-docs milestones/04-map.md
// ("Local preview approach" / Stage 2) for why this is a bundled file rather
// than a live endpoint.

export interface Station {
  id: string
  name: string
  lat: number
  lon: number
}

export interface Route {
  id: string
  name: string
  color: string
  stationIds: string[]
  /** [lon, lat] pairs tracing the real rail alignment (GTFS shapes.txt),
   * not a straight line between stations. Falls back to straight-line
   * station coordinates only if the build script found no usable shape
   * for a route (see build_web_geometry.py). */
  shape: [number, number][]
}

export interface Bounds {
  west: number
  east: number
  south: number
  north: number
}

export interface Geometry {
  stations: Station[]
  routes: Route[]
  bounds: Bounds
}

export const geometry = geometryData as Geometry

export const stationsById = new Map(geometry.stations.map((s) => [s.id, s]))
