import vlineGeometryData from './data/vline-geometry.json'
import { buildGeometryIndex, type Geometry } from './geometry'

// Generated by service/scripts/build_web_geometry.py --mode 1 from the
// static GTFS V/Line-mode snapshot. Same bundled-file-not-live-endpoint
// convention as geometry.ts.

export const vlineGeometry = vlineGeometryData as Geometry

const vlineIndex = buildGeometryIndex(vlineGeometry)
export const vlineStationsById = vlineIndex.stationsById
export const vlineRoutesById = vlineIndex.routesById
export const vlineRoutesByStationId = vlineIndex.routesByStationId

// V/Line trains all render in one brand colour (see build_web_geometry.py's
// VLINE_BRAND_COLOR override) -- individual corridor identity on the map
// comes from line style instead (PTV's official branding has no per-route
// colour to show, see the design addendum). Keyed by route NAME, not
// route_id, since a corridor generally has 2-3 route_ids sharing one name
// (branch/direction variants) that should render identically.
export type LineStyle = 'solid' | 'dashed' | 'dotted' | 'dash-dot' | 'long-dash'

const LINE_STYLE_BY_ROUTE_NAME: Record<string, LineStyle> = {
  Ballarat: 'solid',
  Bendigo: 'dashed',
  Geelong: 'dotted',
  Seymour: 'dash-dot',
  Traralgon: 'long-dash',
}

// MapLibre `line-dasharray` values, in units of line width. `undefined`
// (solid) omits the property entirely rather than passing an empty array.
export const LINE_DASH_ARRAY: Record<LineStyle, number[] | undefined> = {
  solid: undefined,
  dashed: [2, 2],
  dotted: [0.5, 1.5],
  'dash-dot': [3, 1.5, 0.5, 1.5],
  'long-dash': [4, 2],
}

export function lineStyleForRouteName(routeName: string): LineStyle {
  return LINE_STYLE_BY_ROUTE_NAME[routeName] ?? 'solid'
}
